import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, rm, readFile, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { request } from 'node:http';

test('loopback dashboard API protects writes, serves original bytes, and rejects invalid input',async t=>{
 const dir=await mkdtemp(path.join(tmpdir(),'career-api-'));const resume=path.join(dir,'source.pdf');await writeFile(resume,'%PDF-1.4 mock original',{mode:0o600});
 const child=spawn(process.execPath,['--import','tsx','server/index.ts'],{cwd:process.cwd(),env:{...process.env,CAREER_DATA_DIR:path.join(dir,'.data'),CAREER_RESUME_PATH:resume,CAREER_BACKEND:'sqlite',PORT:'0'},stdio:['ignore','pipe','pipe']});
 let output='';let errors='';child.stderr.on('data',b=>{errors+=b.toString();});
 t.after(async()=>{child.kill('SIGTERM');await new Promise<void>(resolve=>{if(child.exitCode!==null)resolve();else {const timer=setTimeout(()=>{child.kill('SIGKILL');resolve();},2000);child.once('exit',()=>{clearTimeout(timer);resolve();});}});await rm(dir,{recursive:true,force:true});});
 const base=await new Promise<string>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(`Server startup timeout: ${errors}`)),15000);child.stdout.on('data',b=>{output+=b.toString();const match=output.match(/Career Agent ready: (http:\/\/127\.0\.0\.1:\d+)/);if(match){clearTimeout(timer);resolve(match[1]);}});child.once('exit',code=>{clearTimeout(timer);reject(new Error(`Server exited ${code}: ${errors}`));});});
 const state=await fetch(`${base}/api/state`).then(r=>r.json()) as any;assert.equal(state.meta.backend,'sqlite');assert.equal(state.meta.resumeValid,true);assert.equal(state.profile.authorizationNow,null);
 const claudePrompt=await fetch(`${base}/api/agent-prompt?mode=prepare&provider=claude`).then(r=>r.json()) as any;assert.match(claudePrompt.prompt,/Use \/job-application-agent/);assert.doesNotMatch(claudePrompt.prompt,/\$job-application-agent/);assert.match(claudePrompt.prompt,/Act as The Goat/);
 assert.equal((await fetch(`${base}/api/agent-prompt?provider=invalid`)).status,400);
 assert.equal((await fetch(`${base}/api/agent-prompt?mode=automatic`)).status,400);
 const legacyPrompt=await fetch(`${base}/api/codex-prompt?mode=accounts`).then(r=>r.json()) as any;assert.match(legacyPrompt.prompt,/\$job-application-agent/);
 const resumeResponse=await fetch(`${base}/api/resume`);assert.equal(resumeResponse.status,200);assert.match(resumeResponse.headers.get('content-disposition')||'',/source\.pdf/);const bytes=new Uint8Array(await resumeResponse.arrayBuffer());assert.equal(createHash('sha256').update(bytes).digest('hex'),state.profile.resume.sha256);
 const post=(body:unknown,headers:Record<string,string>={})=>fetch(`${base}/api/settings`,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
 assert.equal((await post({dailyLimit:5})).status,403);
 assert.equal((await post({dailyLimit:5},{'X-Career-Agent':'dashboard',Origin:'https://malicious.example'})).status,403);
 assert.equal((await post({dailyLimit:21},{'X-Career-Agent':'dashboard'})).status,400);
 assert.equal((await post({dailyLimit:5},{'X-Career-Agent':'dashboard'})).status,200);
 const badHost=await new Promise<number|undefined>((resolve,reject)=>{const req=request(`${base}/api/state`,{headers:{Host:'attacker.example'}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);req.end();});assert.equal(badHost,403);
 const confirmation=await fetch(`${base}/api/approvals`,{method:'POST',headers:{'Content-Type':'application/json','X-Career-Agent':'dashboard'},body:JSON.stringify({packetIds:[]})});assert.equal(confirmation.status,400);
 const profilePatch=await fetch(`${base}/api/profile`,{method:'POST',headers:{'Content-Type':'application/json','X-Career-Agent':'dashboard'},body:JSON.stringify({graduation:'2028-05'})});assert.equal(profilePatch.status,200);assert.equal((await profilePatch.json() as any).graduation,'2028-05');
 const badProfile=await fetch(`${base}/api/profile`,{method:'POST',headers:{'Content-Type':'application/json','X-Career-Agent':'dashboard'},body:JSON.stringify({authorizationNow:'guess'})});assert.equal(badProfile.status,400);
 const onboarding=(body:unknown)=>fetch(`${base}/api/onboarding`,{method:'POST',headers:{'Content-Type':'application/json','X-Career-Agent':'dashboard'},body:JSON.stringify(body)});
 const invalidSetup=await onboarding({profile:{name:'Must not be saved'},settings:{careerStage:'experienced',yearsExperience:null,careerTargetsConfirmed:true}});
 assert.equal(invalidSetup.status,400);assert.equal((await fetch(`${base}/api/state`).then(r=>r.json()) as any).profile.name,'','Invalid setup must not save half a profile');
 const savedSetup=await onboarding({profile:{name:'Jamie Example',email:'jamie@example.test',phone:'+1 202-555-0110',authorizationNow:true,authorizationAtStart:true,futureSponsorship:false,authorizationConfirmedAt:new Date().toISOString()},settings:{careerStage:'early_career',rolePriority:['design'],roleKeywords:['UX designer'],careerTargetsConfirmed:true,applicationPreferences:{writtenAnswers:'draft',formFilling:'agent',submission:'review',confirmedAt:new Date().toISOString(),automaticRiskAccepted:false},preferredLocations:['Chicago'],targetEmployers:['Northstar Labs'],preferredCareerSites:['https://northstar.example/careers'],workplacePreference:'hybrid'}});
 assert.equal(savedSetup.status,200,await savedSetup.text());
 const work=await fetch(`${base}/api/work`).then(r=>r.json()) as any;
 assert.deepEqual(work.setupGaps,[]);assert.deepEqual(work.criteria.preferredLocations,['Chicago']);assert.deepEqual(work.criteria.targetEmployers,['Northstar Labs']);assert.deepEqual(work.criteria.preferredCareerSites,['https://northstar.example/careers']);assert.equal(work.criteria.workplacePreference,'hybrid');
 assert.equal((await fetch(`${base}/api/work?limit=1000`)).status,400);
 assert.equal((await fetch(`${base}/api/agent-prompt?mode=invalid`)).status,400);
 await writeFile(state.profile.resume.path,'%PDF-1.4 tampered');assert.equal((await fetch(`${base}/api/resume`)).status,409);
 const backup=await fetch(`${base}/api/export`);assert.match(backup.headers.get('content-disposition')||'',/attachment/);assert.equal((await backup.json() as any).settings.dailyLimit,5);
});

test('fresh install accepts dashboard answers and original PDF without a terminal résumé path', async t => {
 const dir=await mkdtemp(path.join(tmpdir(),'career-onboard-'));
 const dataDir=path.join(dir,'.data');
 const child=spawn(process.execPath,['--import','tsx','server/index.ts'],{cwd:process.cwd(),env:{...process.env,CAREER_DATA_DIR:dataDir,CAREER_RESUME_PATH:'',CAREER_BACKEND:'sqlite',PORT:'0'},stdio:['ignore','pipe','pipe']});
 let output='';let errors='';child.stderr.on('data',b=>{errors+=b.toString();});
 t.after(async()=>{child.kill('SIGTERM');await new Promise<void>(resolve=>{if(child.exitCode!==null)resolve();else {const timer=setTimeout(()=>{child.kill('SIGKILL');resolve();},2000);child.once('exit',()=>{clearTimeout(timer);resolve();});}});await rm(dir,{recursive:true,force:true});});
 const base=await new Promise<string>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(`Server startup timeout: ${errors}`)),15000);child.stdout.on('data',b=>{output+=b.toString();const match=output.match(/Career Agent ready: (http:\/\/127\.0\.0\.1:\d+)/);if(match){clearTimeout(timer);resolve(match[1]);}});child.once('exit',code=>{clearTimeout(timer);reject(new Error(`Server exited ${code}: ${errors}`));});});
 const post=(route:string,body:unknown)=>fetch(`${base}${route}`,{method:'POST',headers:{'Content-Type':'application/json','X-Career-Agent':'dashboard'},body:JSON.stringify(body)});
 const initial=await fetch(`${base}/api/state`).then(r=>r.json()) as any;
 assert.equal(initial.meta.resumeValid,false);
 assert.equal(initial.profile.resume.filename,'');
 assert.equal((await post('/api/resume/upload',{filename:'resume.txt',base64:Buffer.from('%PDF-1.4 fixture').toString('base64')})).status,400);
 const saved=await post('/api/onboarding',{profile:{name:'Taylor Example',email:'taylor@example.test',phone:'+1 202-555-0100',facts:[{id:'candidate-highlights',label:'Skills and experience highlights',value:'Python and SQL projects',source:'user:confirmed-dashboard',confirmed:true}],portfolioLinks:[{id:'portfolio-1',label:'Data projects',url:'https://portfolio.example.test/projects',notes:'Use for data roles asking for project links.'}],authorizationNow:true,authorizationAtStart:true,futureSponsorship:false,authorizationConfirmedAt:new Date().toISOString()},settings:{careerStage:'early_career',rolePriority:['data'],careerTargetsConfirmed:true,applicationPreferences:{writtenAnswers:'draft',formFilling:'agent',submission:'review',confirmedAt:new Date().toISOString(),automaticRiskAccepted:false}}});
 assert.equal(saved.status,200,await saved.text());
 const privateProfile=JSON.parse(await readFile(path.join(dataDir,'skills','candidate-profile','profile.json'),'utf8'));
 assert.equal(privateProfile.profile.name,'Taylor Example');
 assert.equal(privateProfile.profile.facts.find((fact:any)=>fact.id==='candidate-highlights').value,'Python and SQL projects');
 assert.deepEqual(privateProfile.profile.portfolioLinks,[{id:'portfolio-1',label:'Data projects',url:'https://portfolio.example.test/projects',notes:'Use for data roles asking for project links.'}]);
 assert.match(await readFile(path.join(dataDir,'skills','candidate-profile','SKILL.md'),'utf8'),/portfolioLinks.*factIds/);
 assert.equal((await post('/api/profile',{portfolioLinks:[{id:'unsafe',label:'Unsafe',url:'javascript:alert(1)',notes:''}]})).status,400);
 assert.deepEqual((await fetch(`${base}/api/state`).then(r=>r.json()) as any).profile.portfolioLinks,privateProfile.profile.portfolioLinks);
 assert.equal((await stat(path.join(dataDir,'skills','candidate-profile','profile.json'))).mode & 0o777,0o600);
 const pdf=Buffer.from('%PDF-1.4 original browser upload');
 const uploaded=await post('/api/resume/upload',{filename:'Original Resume.pdf',base64:pdf.toString('base64')});
 assert.equal(uploaded.status,200,await uploaded.text());
 const ready=await fetch(`${base}/api/state`).then(r=>r.json()) as any;
 assert.equal(ready.meta.resumeValid,true);
 assert.equal(ready.profile.resume.filename,'Original Resume.pdf');
 assert.deepEqual(await readFile(ready.profile.resume.path),pdf);
 const transcript=Buffer.from('%PDF-1.4 original transcript upload');
 const transcriptUpload=await post('/api/documents/upload',{filename:'Transcript.pdf',base64:transcript.toString('base64'),kind:'transcript',documentDate:'2026-05-15'});
 assert.equal(transcriptUpload.status,200,await transcriptUpload.clone().text());
 const transcriptRecord=await transcriptUpload.json() as any;
 assert.equal(transcriptRecord.kind,'transcript'); assert.equal(transcriptRecord.documentDate,'2026-05-15');
 assert.deepEqual(await readFile(transcriptRecord.path),transcript);
 assert.equal((await stat(transcriptRecord.path)).mode & 0o777,0o600);
 assert.equal((await fetch(`${base}/api/documents/${transcriptRecord.id}`)).status,200);
 const baseLetter=Buffer.from('%PDF-1.4 base cover letter reference');
 const baseUpload=await post('/api/documents/upload',{filename:'Base Letter.pdf',base64:baseLetter.toString('base64'),kind:'base_cover_letter'});
 assert.equal(baseUpload.status,200,await baseUpload.clone().text());
 const baseRecord=await baseUpload.json() as any;
 assert.equal(baseRecord.kind,'base_cover_letter'); assert.deepEqual(await readFile(baseRecord.path),baseLetter);
 const duplicate=await post('/api/documents/upload',{filename:'Base Letter.pdf',base64:baseLetter.toString('base64'),kind:'base_cover_letter'});
 assert.equal((await duplicate.json() as any).id,baseRecord.id);
 assert.equal((await post('/api/documents/upload',{filename:'fake.pdf',base64:Buffer.from('not a PDF').toString('base64'),kind:'transcript'})).status,400);
 const privateDocuments=JSON.parse(await readFile(path.join(dataDir,'skills','candidate-profile','profile.json'),'utf8')).profile.documents;
 assert.equal(privateDocuments.length,2);
 const work=await fetch(`${base}/api/work`).then(r=>r.json()) as any;
 assert.deepEqual(work.setupGaps,[]);
});
