import test from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { act, createElement } from 'react';
import type { AppSnapshot, CandidateProfile, Settings } from '../shared/types.js';
import StartHere from '../src/StartHere.js';

test('saved intake refreshes clean values, preserves dirty edits, and keeps city/state locations intact', async t => {
 const dom = new JSDOM('<div id="root"></div>', { url: 'http://127.0.0.1:4317' });
 const globals = globalThis as Record<string, any>;
 const previous = { window: globals.window, document: globals.document, navigator: Object.getOwnPropertyDescriptor(globalThis, 'navigator'), IS_REACT_ACT_ENVIRONMENT: globals.IS_REACT_ACT_ENVIRONMENT };
 globals.window = dom.window; globals.document = dom.window.document; Object.defineProperty(globalThis, 'navigator', { value: dom.window.navigator, configurable: true }); globals.IS_REACT_ACT_ENVIRONMENT = true;
 const { createRoot } = await import('react-dom/client'); const root = createRoot(dom.window.document.getElementById('root')!);
 t.after(async () => { await act(async () => root.unmount()); dom.window.close(); globals.window = previous.window; globals.document = previous.document; globals.IS_REACT_ACT_ENVIRONMENT = previous.IS_REACT_ACT_ENVIRONMENT; if (previous.navigator) Object.defineProperty(globalThis, 'navigator', previous.navigator); else delete globals.navigator; });
 let state = {
  profile: { name: 'Alex Example', email: 'alex@example.test', phone: '+1 202-555-0100', graduation: '', authorizationNow: true, authorizationAtStart: true, futureSponsorship: false, authorizationConfirmedAt: '2026-10-02T12:00:00Z', earliestStart: null, facts: [{ id: 'mechanical-projects', label: 'Mechanical project evidence', value: 'Designed and tested a student robot gripper in SolidWorks.', source: 'user:confirmed-dashboard', confirmed: true }], savedAnswers: [{ id: 'legacy-relocation', question: 'Are you willing to relocate?', answer: 'Yes', confirmedAt: '2026-10-02T12:00:00Z' }], resume: { filename: 'original.pdf' } },
  settings: { careerStage: 'early_career', yearsExperience: 2, careerTargetsConfirmed: true, rolePriority: ['design'], roleKeywords: [], preferredLocations: ['Chicago, IL', 'Austin, TX'], targetEmployers: ['Northstar Labs', 'Acme Health'], workplacePreference: 'any', minimumAnnualCompensation: 0, applicationPreferences: { writtenAnswers: 'draft', formFilling: 'agent', submission: 'review', confirmedAt: '2026-10-02T12:00:00Z', automaticRiskAccepted: false } },
  boards: [{ id: 'greenhouse:example', company: 'Example', source: 'greenhouse', token: 'example', enabled: true, sponsorship: [] }],
  packets: [], approvals: [], jobs: [], attempts: [], meta: { resumeValid: true, workspace: 'synthetic-workspace' },
 } as unknown as AppSnapshot;
 let saved: { profile: Partial<CandidateProfile>; settings: Partial<Settings> } | undefined;
 let searches = 0;
 const render = async () => { await act(async () => root.render(createElement(StartHere, { state, busy: false, save: async body => { saved = body; return true; }, search: () => { searches++; }, prepare: () => {}, applyAutomatically: () => {}, submit: () => {}, review: () => {}, uploadResume: async () => true, uploadDocument: async () => true }))); };
 await render();
 const documentSection = dom.window.document.querySelector('#start-documents')!;
 assert.ok(documentSection.compareDocumentPosition(dom.window.document.querySelector('.start-actions')!) & dom.window.Node.DOCUMENT_POSITION_FOLLOWING, 'Documents should be the first setup section');
 assert.deepEqual(Array.from(documentSection.querySelectorAll<HTMLInputElement>('input[type=file]')).map(input => input.getAttribute('aria-label')), ['Replace original résumé PDF', 'Base cover letter PDF', 'Academic transcript PDF']);
 await act(async () => Array.from(dom.window.document.querySelectorAll('button')).find(button => button.textContent?.includes('Search employer feeds now'))!.click());
 assert.equal(searches,1,'Start here must launch dashboard discovery directly');
 state = { ...state, boards: [] }; await render();
 assert.equal(Array.from(dom.window.document.querySelectorAll('button')).find(button => button.textContent?.includes('Search employer feeds now'))?.disabled, true);
 assert.match(dom.window.document.querySelector('.start-action-help')?.textContent || '', /No feeds are configured yet/);
 state = { ...state, profile: { ...state.profile, name: 'Updated Example' } }; await render();
 const buttons = () => Array.from(dom.window.document.querySelectorAll('button'));
 await act(async () => buttons().find(button => button.textContent === 'Edit my saved preferences')!.click());
 const submissionOptions = Array.from(dom.window.document.querySelectorAll<HTMLInputElement>('input[name="submission-mode"]'));
 assert.deepEqual(submissionOptions.map(input => input.closest('label')?.querySelector('b')?.textContent), ['I click Submit', 'Adi submits batches I approve', 'Adi finds, fills, and submits for me']);
 assert.equal(submissionOptions.find(input => input.value === 'review')?.checked, true);
 await act(async () => submissionOptions.find(input => input.value === 'automatic')!.click());
 assert.match(dom.window.document.querySelector('.start-risk')?.textContent || '', /without my review of each one/);
 await act(async () => dom.window.document.querySelector<HTMLInputElement>('.start-risk input')!.click());
 assert.equal(dom.window.document.querySelector<HTMLInputElement>('input[type="number"][max="2"]')?.value, '2', 'Early-career experience is saved as an exact count');
 assert.equal(dom.window.document.querySelector<HTMLAnchorElement>('.start-intake-map-identity')?.getAttribute('href'), '#start-self-id');
 assert.equal(dom.window.document.querySelector<HTMLDetailsElement>('#start-search-priorities')?.open, true, 'Search priorities are visible during onboarding');
 const identitySection = dom.window.document.querySelector<HTMLElement>('#start-self-id')!;
 assert.ok(identitySection.compareDocumentPosition(dom.window.document.querySelector('#start-background')!) & dom.window.Node.DOCUMENT_POSITION_FOLLOWING, 'Voluntary identity appears before the long background bank');
 assert.equal(identitySection.querySelector('h3')?.textContent, 'Veteran and military service');
 const name = dom.window.document.querySelector<HTMLInputElement>('input[autocomplete="name"]')!;
 assert.equal(name.value, 'Updated Example', 'Clean editor must read the newest profile');
 const locationInput = Array.from(dom.window.document.querySelectorAll<HTMLInputElement>('input')).find(input => input.placeholder.includes('Chicago'))!;
 assert.equal(locationInput.value, 'Chicago, IL; Austin, TX');
 const select = Array.from(dom.window.document.querySelectorAll<HTMLSelectElement>('select')).find(element => element.closest('label')?.textContent?.includes('Workplace preference'))!;
 await act(async () => { select.value = 'remote'; select.dispatchEvent(new dom.window.Event('change', { bubbles: true })); });
 const selfId = (label: string) => Array.from(dom.window.document.querySelectorAll<HTMLSelectElement>('select')).find(element => element.closest('label')?.querySelector('span')?.textContent === label)!;
 const startupSection = Array.from(dom.window.document.querySelectorAll<HTMLDetailsElement>('details')).find(element => element.querySelector('summary')?.textContent?.includes('Startups and product teams'))!;
 startupSection.open = true;
 const startupProject = startupSection.querySelector<HTMLTextAreaElement>('textarea')!;
 await act(async () => { Object.getOwnPropertyDescriptor(dom.window.HTMLTextAreaElement.prototype, 'value')!.set!.call(startupProject, 'Shipped a scheduling feature used by 200 customers.'); startupProject.dispatchEvent(new dom.window.Event('input', { bubbles: true })); });
 assert.equal(startupSection.open, true, 'An opened industry section stays open while its answer is edited');
 assert.equal(selfId('Gender').value, '', 'Optional self-identification starts unanswered');
 await act(async () => { selfId('Gender').value = "I don't wish to answer"; selfId('Gender').dispatchEvent(new dom.window.Event('change', { bubbles: true })); });
 await act(async () => { selfId('Hispanic or Latino').value = 'Yes'; selfId('Hispanic or Latino').dispatchEvent(new dom.window.Event('change', { bubbles: true })); });
 await act(async () => { selfId('Protected veteran status').value = 'I am not a protected veteran'; selfId('Protected veteran status').dispatchEvent(new dom.window.Event('change', { bubbles: true })); });
 await act(async () => { selfId('Currently a full-time student').value = 'No'; selfId('Currently a full-time student').dispatchEvent(new dom.window.Event('change', { bubbles: true })); });
 await act(async () => { selfId('Ever held an insurance or securities industry license').value = 'No'; selfId('Ever held an insurance or securities industry license').dispatchEvent(new dom.window.Event('change', { bubbles: true })); });
 const educationHistory = Array.from(dom.window.document.querySelectorAll<HTMLTextAreaElement>('#start-background textarea')).find(element => element.closest('label')?.textContent?.includes('List your schools'))!;
 await act(async () => { Object.getOwnPropertyDescriptor(dom.window.HTMLTextAreaElement.prototype, 'value')!.set!.call(educationHistory, 'Midwest University, BS Mechanical Engineering, Chicago, 08/2022–05/2026.'); educationHistory.dispatchEvent(new dom.window.Event('input', { bubbles: true })); });
 await act(async () => Array.from(dom.window.document.querySelectorAll<HTMLButtonElement>('#start-work-samples button')).find(button => button.textContent === 'Add another link')!.click());
 const workLink = dom.window.document.querySelector<HTMLElement>('.start-link-card')!;
 const setField = async (element: HTMLInputElement | HTMLTextAreaElement, value: string) => { await act(async () => { Object.getOwnPropertyDescriptor(element instanceof dom.window.HTMLTextAreaElement ? dom.window.HTMLTextAreaElement.prototype : dom.window.HTMLInputElement.prototype, 'value')!.set!.call(element, value); element.dispatchEvent(new dom.window.Event('input', { bubbles: true })); }); };
 const linkInputs = workLink.querySelectorAll<HTMLInputElement>('input');
 await setField(linkInputs[0], 'Mechanical design portfolio');
 await setField(linkInputs[1], 'https://portfolio.example.test/mechanical');
 await setField(workLink.querySelector<HTMLTextAreaElement>('textarea')!, 'Use for CAD and prototyping roles.');
 state = { ...state, settings: { ...state.settings, workplacePreference: 'hybrid' } }; await render();
 assert.equal(select.value, 'remote', 'Refresh must preserve a current unsaved choice');
 assert.equal(workLink.querySelector<HTMLInputElement>('input')?.value, 'Mechanical design portfolio', 'Refresh must preserve an unsaved portfolio link');
 await act(async () => dom.window.document.querySelector('form')!.dispatchEvent(new dom.window.Event('submit', { bubbles: true, cancelable: true })));
 assert.equal(saved?.settings.applicationPreferences?.submission, 'automatic');
 assert.equal(saved?.settings.applicationPreferences?.automaticRiskAccepted, true);
 assert.equal(saved?.profile.name, 'Updated Example'); assert.deepEqual(saved?.settings.preferredLocations, ['Chicago, IL', 'Austin, TX']); assert.deepEqual(saved?.settings.targetEmployers, ['Northstar Labs', 'Acme Health']); assert.equal(saved?.settings.workplacePreference, 'remote');
 assert.equal(saved?.profile.savedAnswers?.find(answer => answer.question === 'Are you open to relocation?')?.answer, 'Yes');
 assert.equal(saved?.profile.savedAnswers?.some(answer => answer.question === 'Are you willing to relocate?'), false, 'Legacy aliases must not conflict with new preferences');
 assert.equal(saved?.profile.savedAnswers?.find(answer => answer.question === 'Gender')?.answer, "I don't wish to answer");
 assert.equal(saved?.profile.savedAnswers?.find(answer => answer.question === 'Are you Hispanic/Latino?')?.answer, 'Yes');
 assert.equal(saved?.profile.savedAnswers?.find(answer => answer.question === 'Veteran Status')?.answer, 'I am not a protected veteran');
 assert.equal(saved?.profile.savedAnswers?.find(answer => answer.question === 'Are you currently a full-time student?')?.answer, 'No');
 assert.equal(saved?.profile.savedAnswers?.find(answer => answer.question === 'Have you ever been licensed in the insurance or securities industry?')?.answer, 'No');
 assert.equal(saved?.profile.savedAnswers?.some(answer => answer.question === 'Sexual Orientation'), false, 'Unanswered sensitive questions are not saved');
 assert.equal(saved?.profile.facts?.find(fact => fact.id === 'mechanical-projects')?.value, 'Designed and tested a student robot gripper in SolidWorks.');
 assert.equal(saved?.profile.facts?.find(fact => fact.id === 'startup-products')?.value, 'Shipped a scheduling feature used by 200 customers.');
 assert.equal(saved?.profile.facts?.find(fact => fact.id === 'education-history')?.value, 'Midwest University, BS Mechanical Engineering, Chicago, 08/2022–05/2026.');
 assert.deepEqual(saved?.profile.portfolioLinks?.map(link => ({ label: link.label, url: link.url, notes: link.notes })), [{ label: 'Mechanical design portfolio', url: 'https://portfolio.example.test/mechanical', notes: 'Use for CAD and prototyping roles.' }]);
 state = { ...state, profile: { ...state.profile, ...saved!.profile } }; await render();
 await act(async () => buttons().find(button => button.textContent === 'Edit my saved preferences')!.click());
 assert.equal(dom.window.document.querySelectorAll('.start-link-card').length, 1, 'Saved link is editable on a later visit');
 await act(async () => dom.window.document.querySelector<HTMLButtonElement>('.start-link-card button')!.click());
 await act(async () => dom.window.document.querySelector('form')!.dispatchEvent(new dom.window.Event('submit', { bubbles: true, cancelable: true })));
 assert.deepEqual(saved?.profile.portfolioLinks, [], 'Removing a link clears it from the next saved profile');
});
